{% set version = "0.7.3" %}

package:
  name: netcdf-scm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/netcdf-scm/netcdf-scm-{{ version }}.tar.gz
  sha256: 0b5103d2ed158e88fe8392e4c1d79aea795f409da0bd26501976e1c18d32a9bd

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - iris
    - cftime
    - nc-time-axis

test:
  imports:
    - netcdf_scm

about:
  home: https://github.com/znicholls/netcdf-scm
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python wrapper for processing netCDF files for use with simple climate models
  doc_url: https://github.com/znicholls/netcdf-scm
  dev_url: https://netcdf-scm.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - znicholls
