{% set version = "2.0.0rc4" %}

package:
  name: netcdf-scm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/netcdf-scm/netcdf-scm-{{ version }}.tar.gz
  sha256: 96ceb6e76f99a29a13973d33d88aac30be849d26f63131ff2f2feb13da5f61a3

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - click
    - iris
    - numpy
    - python-dateutil
    - pymagicc
    - scipy
    - tqdm

test:
  imports:
    - netcdf_scm

  commands:
    - python -c "import netcdf_scm; assert netcdf_scm.__version__ == '{{ version }}'"

about:
  home: https://gitlab.com/netcdf-scm/netcdf-scm
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python wrapper for processing netCDF files for use with simple climate models
  doc_url: https://netcdf-scm.readthedocs.io/en/latest/
  dev_url: https://gitlab.com/netcdf-scm/netcdf-scm

extra:
  recipe-maintainers:
    - znicholls
