{% set version = "2.0.0rc1" %}

package:
  name: netcdf-scm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/netcdf-scm/netcdf-scm-{{ version }}.tar.gz
  sha256: 55041fea184308a23ded5e1a333d414d7baae740fa43c1e8b0531b0d7cf18c7a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - click
    - iris
    - numpy
    - python-dateutil
    - pymagicc
    - scipy
    - tqdm

test:
  imports:
    - netcdf_scm

  commands:
    - python -c "import netcdf_scm; assert netcdf_scm.__version__ == '{{ version }}'"

about:
  home: https://gitlab.com/znicholls/netcdf-scm
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python wrapper for processing netCDF files for use with simple climate models
  doc_url: https://gitlab.com/znicholls/netcdf-scm
  dev_url: https://netcdf-scm.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - znicholls
