{% set version = "0.7.2" %}

package:
  name: netcdf-scm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/netcdf-scm/netcdf-scm-{{ version }}.tar.gz
  sha256: fc1c3a9af54b212962a0134a3f6751fd22eb594fac9f69fbcd4c5107474cf860

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - iris
    - cftime
    - nc-time-axis

test:
  imports:
    - netcdf_scm

about:
  home: https://github.com/znicholls/netcdf-scm
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python wrapper for processing netCDF files for use with simple climate models
  doc_url: https://github.com/znicholls/netcdf-scm
  dev_url: https://netcdf-scm.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - znicholls
