travis:
  secure:
    BINSTAR_TOKEN: MGYb8Yh2W1TvDTHToIcwyEj1RHPnuv+stYNypFsw5TzOKLbrZ+CzKhSHRCavTjfhFoLg/BPB7RkjZEXU+i8jsqXf1EXRoVnw9GNYSZxSp7hD4EtitpfT+X1djxtfxTLhIeTqJcpXPz5W7+soY6fx9/r/YEyx75wkJgNyAhVwO1hNdb88PgJm+rawPSo/QfYmMOr88YPmy5JKkzZpLw6VzBtFGO45omcxo7qxols0TXZn/vp6+i5MJUwMcg1hmHZ2+VxMXSrs97w0QHfGoElHYcJkI3VOzO8vwDLjOQmE4gWZobP4sanksuHR3UTTYRS5CJidh+oCRyTZQj9zufkPXS8bAwptn4RkBZ7nJBUz3EWzcsgfS+KapeZrRztajnYjFvE0CuNE9F/Atw3//fVT7q4p+CQX1WiXH4EhUfFgcwm3mv3sYDhUg/5MEPpO7XQk/hZv2lJdb5bpUSEsdutRddiyPBb24XtUDscW+/6EYKl4VrovCWT9KfbSH+GJoz5ttVix2+JvKXGPPFqsaMRVRSHRUkvr/+fVPEC0+PjHAT59PPgDcGP0knTnvIU9OR7oJLoygwiu+QEdzucj4EZNe6/AWk1WKoyNp01cEUssdQAFKE490wjA0ytmKxUkrUYzmwRD8XUHhuHaO+WUFifPTtjE2lxRuVWwRpFoRdCPEmc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
